### ISSUE TITLE
SecurityProtocol not specified when sending a request

### ISSUE THREAD

**Issue by AndySchmitt** [Strumenta/SmartReader#10]
SmartReader does not specify Security Protocols after the creation of HttpClient, this causes a 502 bad gateway response from server.

I solved this problem specifying the SecurityProtocol after the creation of HttpClient:

> ServicePointManager.SecurityProtocol = SecurityProtocolType.Ssl3 | SecurityProtocolType.Tls | SecurityProtocolType.Tls11 | SecurityProtocolType.Tls12;

Here is a test case:
https://girosa.com.br/politica/empresa-que-presta-servicos-em-osasco-integra-consorcio-do-lixo-investigado-pela-pf

**Comment by unosviluppatore** [comment]
Thanks for indicating the problem. 

I will try to fix it this weekend. However, security is complicated, so I will have to research first what combinations of values creates the least problems. It might take sometimes.

**Comment by unosviluppatore** [comment]
I do not think I will fix this issue, but I have added a note about it in the README.

I think that this is the best way because any change on the property `ServicePointManager.SecurityProtocol` might affect also requests made by other parts of the code (see [documentation](https://docs.microsoft.com/en-us/dotnet/api/system.net.servicepointmanager.securityprotocol?view=netcore-2.0)). This will be unexpected and might cause weird bugs to some user of the library.
