### ISSUE TITLE
New Bug: Featured Image seems to only provide asset name in the latest version instead of full url

### ISSUE THREAD

**Issue by alombard** [Strumenta/SmartReader#11]
Hello,

First off let me say that this is a wonderful port of the Mozilla framework.

I wanted to flag something I've observed since upgrading from 0.5.2 to the latest version (it seems that every update since 5.2 has the same issue as I've tested a few).

Once an article is parsed from the URL below via the following snippet:

```
var url = "https://www.latimes.com/world-nation/story/2019-08-02/antarctica-polar-star-icebreaker?utm_source=pocket-newtab";
SmartReader.Article article = SmartReader.Reader.ParseArticle(url);
```
I'm seeing two behaviors for `article.FeaturedImage` for some of the pages which had previously worked in my tests.

Prior to version 0.6 the framework extracts the  FeaturedImage url as:
`https://ca-times.brightspotcdn.com/dims4/default/51707d7/2147483647/strip/true/crop/5556x2917+0+396/resize/1200x630!/quality/90/?url=https%3A%2F%2Fca-times.brightspotcdn.com%2F0f%2Fdd%2Fa2b0188a4b869f5da4007bb00323%2Fla-photos-1staff-3082510-la-na-polar-star-toned-102.jpg`

Post Version 0.6 the following is extracted for the FeaturedImage url:
`'3082510_la-na-polar-star_TONED_102.jpg'`

Is there something I'm doing incorrectly in the newer versions of the framework (eg. do I need to build the full URL?) or is this a bug?  For now I've simply downgraded to work around this but am not sure if I this is intended functionality or not.  

Thanks in advance for your time and appreciate your great work on this!

Andrew

**Comment by unosviluppatore** [comment]
Thanks for your feedback and precise bug report.

This is indeed a bug. Looking at the source of the webpage you mentioned I can see that they both appear in (different) meta tags: the first one in _og:image_ and _twitter:image_ and the second one in _og:image:alt_ and _twitter:image:alt_. But the *:alt tags should not be searched for a featured image, so this is a bug in the algorithm that recognizes the meta tags in which to look for images. 

The bug is present from the version you mentioned probably because in that version I fixed some other metadata-related bugs, some tags were not recognized at all.

I will look into fixing the bug this weekend.

**Comment by alombard** [comment]
🙌 Thanks very much Gabriele!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
