### ISSUE TITLE
Thresholds must be language sensitive

### ISSUE THREAD

**Issue by ivanicin** [Strumenta/SmartReader#47]
Thresholds like `MinContentLengthReadearable ` must be language sensitive. For example the default values work quite well for English. But for Chinese they should be something like 8x lower.

The obvious problem is that one doesn't know the language of the document ahead in most cases. As such one cannot provide proper threshold values. Even worse defaults don't work properly if they are constant across languages.

I would suggest to implement this as a `Dictionary `so that one can define the values per language. Or to make those values internally sensitive to languages. Or both.

**Comment by gabriele-tomassetti** [comment]
It is a good idea, the problem is how to implement it. We do have some language-base statistics [to calculate time to read](https://github.com/Strumenta/SmartReader/blob/master/src/SmartReader/TimeToReadCalculator.cs) that we could use as a starting point to infer a valid length. However, we would just guessing which is not a great approach.

I am not sure that we have the data to provide reasonable estimates, but we could transform the `MinContentLengthReadearable` field in a dictionary to allow users to set the values themselves.
