### ISSUE TITLE
Pass the original html in Article

### ISSUE THREAD

**Issue by ivanicin** [Strumenta/SmartReader#49]
I think that you should pass the original html in `Article `in every case.

However if the `Article ` is not readable then this is the must as one shouldn't download it again.

**Comment by gabriele-tomassetti** [comment]
Personally, I do not think this would be a good approach both because it is not consistent with the class `Article` and most users would not need that. You can already [use custom operations at the beginning of the article to save the original content somewhere else](https://smartreader.inre.me/articles/advanced.html#adding-custom-operations), if you need. Alternatively, with the fix of issue #46, you would be able to obtain the article yourself before passing to SmartReader.

**Comment by ivanicin** [comment]
Then possibly you should just document it as it is likely that people would need it.
