### ISSUE TITLE
Incompatibility with latest version of AngleSharp

### ISSUE THREAD

**Issue by pranavmehta** [Strumenta/SmartReader#8]
Some breaking changes in AngleSharp makes SmartReader incompatible when using with the latest version of AngleSharp

Exception: Could not load type 'AngleSharp.Parser.Html.HtmlParser' from assembly 'AngleSharp, Version=0.11.0.0, Culture=neutral, PublicKeyToken=e83494dcdc6d31ea'.

**Comment by unosviluppatore** [comment]
Thanks for the information. We are going to try fixing the issue during this week.

**Comment by unosviluppatore** [comment]
The issue has been solved in [a new commit](https://github.com/Strumenta/SmartReader/commit/6041d62db789aec8184b7494e2d276fb6438b713). However, this would require to up the minimum platform of SmartReader to .NETStandard 2.0: this is because of AngleSharp.Css.

Upgrading to .NETStandard 1.6 has little consequences, but requiring .NETStandard 2.0 it is a bit more consequential (see [.NET Implementation Support](https://docs.microsoft.com/en-us/dotnet/standard/net-standard#net-implementation-support)) for people using Mono or Xamarin.Android.

I do not have any issue with that, if nobody else has any objection I will release the new version of the library in one week.

**Comment by pranavmehta** [comment]
Thanks a ton! 

I'm guessing the Nuget package will also be updated soon?

**Comment by unosviluppatore** [comment]
Before releasing the Nuget package I am waiting one week, to see if anybody has any issue with the raising of the minimum version from .NETStandard 1.3 to 2.0.
